version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5001:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
